
[project]
name = "ArtGallery"
authors = []
telemetry = true
[repl.analysis]
passes = ["check_checker"]
[repl.analysis.check_checker]
trusted_sender = false
trusted_caller = false
callee_filter = false

[contracts.ArtGallery]
path = "contracts/ArtGallery.clar"
depends_on = []
